name: Build Mac Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pynput Pillow pyinstaller pyautogui --no-dependencies

      - name: Build with PyInstaller
        run: |
          PYTHON_FILE=$(ls *.py | head -n 1)
          python3 -m PyInstaller --noconsole --onefile --windowed --name "504_Tracker" "$PYTHON_FILE"

      - name: Fix Permissions and Zip ON THE MAC SERVER
        run: |
          # This gives the internal file permission to run
          chmod +x dist/504_Tracker.app/Contents/MacOS/504_Tracker
          # This zips the folder while still on a Mac system to save that permission
          cd dist && zip -r ../504_Tracker_Mac_Ready.zip 504_Tracker.app

      - name: Upload Finished ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Tracker-Ready-To-Use
          path: 504_Tracker_Mac_Ready.zip
