name: Build Mac Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyautogui requests pynput Pillow pyinstaller

      - name: Build with PyInstaller
        run: |
          # This command finds the .py file even if the name is slightly different
          PYTHON_FILE=$(ls *.py | head -n 1)
          echo "Building with file: $PYTHON_FILE"
          pyinstaller --noconsole --onefile --windowed --name "504_Digital_Tracker" "$PYTHON_FILE"

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: Mac-Tracker-App
          path: dist/504_Digital_Tracker.app
